version: "3"
services:
  workspace:
    container_name: workspace
    build:
      context: .
    command: "sleep infinity"
    # WARN: only expose really needed ports
    ports:
      - "6060:3000"
    volumes:
      - workspace:/root/repos

volumes:
  workspace:
    name: workspace
