version: "3"
services:
  workspace:
    container_name: workspace
    build:
      context: .
    command: "sleep infinity"
    # WARN: only expose really needed ports
    ports:
      - "6060:3000"
    volumes:
      - workspace:/root/repos
      # WARN: Should use volumes and generate new keys
      - type: bind
        source: ssh
        target: /root/.ssh

volumes:
  workspace:
    name: workspace
